/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.windows;

import controle.ControleLogin;
import controle.ControlePerfil;
import flex.db.GenericDAO;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.negocio.InventarioResumo;
import modelo.negocio.Perfil;
import modelo.negocio.Usuario;
import util.Cast;

/**
 *
 * @author Alexandre
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private final Perfil atual;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        
        initComponents();
        
        Image image = new ImageIcon(getClass().getResource("/visao/images/cattle.png")).getImage();
        this.setIconImage(image);
        
        atual = ControlePerfil.getInstance().getPerfilSelecionado();
        
        Usuario usuario = ControleLogin.getInstance().getUsuario();
        
        if(usuario.getTipoUsuario() == 3) { // Apenas visualização
            addAnoBT.setVisible(false);
        }
        
        super.setTitle("SGPL - " + atual.getNome() + " - Menu Principal");
        super.setLocationRelativeTo(null);
        super.setResizable(false);
        
        nomProd.setText(atual.getNome());
        tamProp.setText(Cast.toBRLocaleValue(atual.getTamPropriedade()));
        nomCida.setText(atual.getCidade());
        
        int anoAnterior = ControlePerfil.getInstance().getAno();
        
        fillComboBox();
        
        if (anoAnterior != ControlePerfil.getInstance().getAno() && anoAnterior != 0) {
            ControlePerfil.getInstance().setAno(anoAnterior);
        }
        
        anoCombo.setSelectedItem(Cast.toString(ControlePerfil.getInstance().getAno()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoEntrada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomProd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tamProp = new javax.swing.JLabel();
        nomCida = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        btnDadosTecnMensais = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnIndicEconMensais = new javax.swing.JButton();
        btnDadosEconMensais = new javax.swing.JButton();
        btnIndicEconAnuais = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        anoCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        addAnoBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoEntrada.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoEntrada.setForeground(new java.awt.Color(0, 38, 255));
        textoEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEntrada.setText("Grupo de Estudo em Gestão Rural");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produtor:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tamanho:");

        nomProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomProd.setText("nome_produtor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cidade:");

        tamProp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tamProp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamProp.setText("tamanho_propriedade");

        nomCida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomCida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomCida.setText("nome_cidade");

        btnPerfil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPerfil.setText("Voltar para Perfis");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnDadosTecnMensais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDadosTecnMensais.setText("Dados Técnicos Mensais");
        btnDadosTecnMensais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosTecnMensaisActionPerformed(evt);
            }
        });

        btnInventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInventario.setText("Inventário");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnIndicEconMensais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIndicEconMensais.setText("Indicadores Mensais");
        btnIndicEconMensais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndicEconMensaisActionPerformed(evt);
            }
        });

        btnDadosEconMensais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDadosEconMensais.setText("Dados Econômicos Mensais");
        btnDadosEconMensais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosEconMensaisActionPerformed(evt);
            }
        });

        btnIndicEconAnuais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIndicEconAnuais.setText("Indicadores Anuais");
        btnIndicEconAnuais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndicEconAnuaisActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 38, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pecuária Leiteira");

        anoCombo.setBackground(new java.awt.Color(0, 153, 255));
        anoCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        anoCombo.setMaximumRowCount(5);
        anoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                anoComboItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 38, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ano:");

        addAnoBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/images/add.png"))); // NOI18N
        addAnoBT.setToolTipText("Adicionar ano");
        addAnoBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnoBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIndicEconMensais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDadosEconMensais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDadosTecnMensais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIndicEconAnuais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(nomCida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nomProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tamProp, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(296, 296, 296))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(203, 203, 203)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textoEntrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addComponent(jLabel3)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addGap(10, 10, 10)
                            .addComponent(anoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addAnoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(addAnoBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tamProp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomCida))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDadosTecnMensais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDadosEconMensais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIndicEconAnuais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIndicEconMensais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        Cursor wait = new Cursor(Cursor.WAIT_CURSOR);
        this.setCursor(wait);
        
        new VisualizarPerfil().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnDadosTecnMensaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosTecnMensaisActionPerformed
        Cursor wait = new Cursor(Cursor.WAIT_CURSOR);
        this.setCursor(wait);
        
        new VisualizarDadosTecnMensais().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnDadosTecnMensaisActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        Cursor wait = new Cursor(Cursor.WAIT_CURSOR);
        this.setCursor(wait);
        
        new VisualizarInventario().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnDadosEconMensaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosEconMensaisActionPerformed
        Cursor wait = new Cursor(Cursor.WAIT_CURSOR);
        this.setCursor(wait);
        
        new VisualizarDadosEconMensais().setVisible(true); 
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnDadosEconMensaisActionPerformed

    private void btnIndicEconMensaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndicEconMensaisActionPerformed
        new PeriodSelector(this, true).setVisible(true);
    }//GEN-LAST:event_btnIndicEconMensaisActionPerformed

    private void btnIndicEconAnuaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndicEconAnuaisActionPerformed
        new MultipleYearSelector(this, true).setVisible(true);
    }//GEN-LAST:event_btnIndicEconAnuaisActionPerformed

    private void anoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_anoComboItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            ControlePerfil.getInstance().setAno(Integer.parseInt(anoCombo.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_anoComboItemStateChanged

    private void addAnoBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnoBTActionPerformed
        boolean existe = false;
        InventarioResumo resumo = null;
        
        SingleYearSelector telaNovoAno = new SingleYearSelector(this, true);
        telaNovoAno.setTitle("SGPL - Adicionar novo ano");
        telaNovoAno.setVisible(true);
        
        String ano = telaNovoAno.getSelected();
        
        if (ano != null) {
            GenericDAO<InventarioResumo> irdao = new GenericDAO<>(InventarioResumo.class);
            List<InventarioResumo> resumos = irdao.retrieveByColumns(new String[] {"idPerfilFK", "ano"}, new Object[] { atual.getId(), ano});

            if(!resumos.isEmpty()) {
                resumo = resumos.get(0);         
            }         

            if (resumo == null) {
                resumo = new InventarioResumo();
                resumo.setIdPerfil(atual.getId());
                resumo.setAno(Integer.parseInt(ano));                               
                irdao.insert(resumo);
            }

            for(int i = 0; i < anoCombo.getItemCount(); i++) {
                if (anoCombo.getItemAt(i).equals(ano)) {
                    existe = true;
                    break;
                }
            }
            if (existe == true) {
                JOptionPane.showMessageDialog(this, "Este ano já foi inserido para o perfil de " + atual.getNome()
                        + ".", "Alerta - Inserção de ano já cadastrado", JOptionPane.WARNING_MESSAGE);
                return;
            }

            anoCombo.addItem(ano);
            anoCombo.setSelectedItem(ano);
        }
    }//GEN-LAST:event_addAnoBTActionPerformed

    private void fillComboBox() {
        GenericDAO<InventarioResumo> dao = new GenericDAO<>(InventarioResumo.class);
        
        List<InventarioResumo> listaAnos = dao.executeSQL("" + 
                "SELECT ano FROM inventario_terras        AS it  WHERE it.idPerfilFK  = " + atual.getId() + " UNION " + 
                "SELECT ano FROM inventario_forrageiras   AS ifo WHERE ifo.idPerfilFK = " + atual.getId() + " UNION " +
                "SELECT ano FROM inventario_maquinas      AS im  WHERE im.idPerfilFK  = " + atual.getId() + " UNION " + 
                "SELECT ano FROM inventario_benfeitorias  AS ib  WHERE ib.idPerfilFK  = " + atual.getId() + " UNION " + 
                "SELECT ano FROM inventario_animais       AS ia  WHERE ia.idPerfilFK  = " + atual.getId() + " UNION " + 
                "SELECT ano FROM inventario_resumo        AS ir  WHERE ir.idPerfilFK  = " + atual.getId() + " UNION " +
                "SELECT ano FROM dados_economicos_mensais AS dem WHERE dem.idPerfilFK = " + atual.getId() + " UNION " +
                "SELECT ano FROM dados_tecnicos_mensais   AS dtm WHERE dtm.idPerfilFK = " + atual.getId() +
                " ORDER BY ano");
        
        if (listaAnos.isEmpty()) {
            Calendar cal = GregorianCalendar.getInstance();
            anoCombo.addItem(Cast.toString(cal.get(Calendar.YEAR)));
        }
        
        for(int i = listaAnos.size() - 1; i >= 0; i--) {
            this.anoCombo.addItem(Cast.toString(listaAnos.get(i).getAno()));
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnoBT;
    private javax.swing.JComboBox<String> anoCombo;
    private javax.swing.JButton btnDadosEconMensais;
    private javax.swing.JButton btnDadosTecnMensais;
    private javax.swing.JButton btnIndicEconAnuais;
    private javax.swing.JButton btnIndicEconMensais;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nomCida;
    private javax.swing.JLabel nomProd;
    private javax.swing.JLabel tamProp;
    private javax.swing.JLabel textoEntrada;
    // End of variables declaration//GEN-END:variables
}
