INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Produção Total de Leite");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Venda de Leite (L)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Venda de Animais(und)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Empréstimos");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Queijo");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Outros(Entrada)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Mão de obra permanente");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Mão de obra temporária");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Energia");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Combustível");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Consumo Interno(produtor e func.)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Leite para Bezerro");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Impostos e Taxas");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Reparos de Benfeitorias");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Reparos de Máquinas");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Outros(Saída)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Gastos Extras");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Compra de volumoso (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Compra de volumoso (Kg)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Calcário (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Adubo químico (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Adubo orgânico comprado (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Serviços mecânicos (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Serviços de tração animal (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Defensivo/veneno (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Frete (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Sementes (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Aluguel de pastagens (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Concentrado rebanho (cria)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Concentrado rebanho (produção)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Fubá de milho");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Farelo de trigo");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Farelo de algodão");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Farelo de soja");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Melaço");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Uréia");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Cama de galinha");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Outros(Concentrado)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Sal comum");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Sal mineral");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Concentrado mineral");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Farinha de ossos");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Fosfato bicálcico");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Mistura preparada na fazenda");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Vermífugos");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Carrapaticida");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Mata-bicheira");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Vacina (aftosa)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Vacina (brucelose)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Vacina (manqueira)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Vacina (raiva)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Vacina (outras)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Antibióticos");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Antitóxicos");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Material de limpeza e desinfecção");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Vitaminas e anti-inflamatório");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Detergentes");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Desinfetantes para tetos");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Materiais");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Outros(Ordenha)");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Sêmen");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Nitrogênio líquido");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Luvas");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Pipetas/bainha");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Inseminador contratado");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Formação de pastagens/Forragem de corte");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Benfeitorias/Instalações/Máquinas");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Aquisição de animais");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Pagamento de empréstimos no mês");
INSERT INTO projeto_pesquisa.dem_especificacao (especificacao) VALUES ("Mão-de-obra familiar (não paga)");