INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Produção Total de Leite");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Venda de Leite (L)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Venda de Animais(und)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Empréstimos");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Queijo");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Outros");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Mão de obra permanente");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Mão de obra temporária");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Energia");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Combustível");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Consumo Interno(produtor e func.)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Leite para Bezerro");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Impostos e Taxas");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Reparos de Benfeitorias");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Reparos de Máquinas");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Outros");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Gastos Extras");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Compra de volumoso (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Compra de volumoso (Kg)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Calcário (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Adubo químico (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Adubo orgânico comprado (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Serviços mecânicos (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Serviços de tração animal (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Defensivo/veneno (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Frete (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Sementes (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Aluguel de pastagens (R$)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Concentrado rebanho (cria)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Concentrado rebanho (produção)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Fubá de milho");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Farelo de trigo");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Farelo de algodão");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Farelo de soja");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Melaço");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Uréia");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Cama de galinha");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Outros");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Sal comum");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Sal mineral");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Concentrado mineral");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Farinha de ossos");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Fosfato bicálcico");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Mistura preparada na fazenda");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Vermífugos");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Carrapaticida");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Mata-bicheira");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Vacina (aftosa)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Vacina (brucelose)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Vacina (manqueira)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Vacina (raiva)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Vacina (outras)");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Antibióticos");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Antitóxicos");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Material de limpeza e desinfecção");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Vitaminas e anti-inflamatório");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Detergentes");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Desinfetantes para tetos");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Materiais");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Outros");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Sêmen");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Nitrogênio líquido");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Luvas");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Pipetas/bainha");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Inseminador contratado");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Formação de pastagens/Forragem de corte");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Benfeitorias/Instalações/Máquinas");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Aquisição de animais");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Pagamento de empréstimos no mês");
INSERT INTO projeto_pesquisa.dem_especificacao VALUES (0, "Mão-de-obra familiar (não paga)");