INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Picadeira de Forragens",  "Ud", 1.0, 3000, 10, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Ordenhadeira Mecânica",   "Ud", 0.0, 5000, 10, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Pulverizador", 		   "Ud", 0.0, 100, 	8, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Motor à Óleo", 		   "Ud", 0.0, 0, 	0, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Arado", 				   "Ud", 0.0, 3500, 10, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Ensiladeira", 			   "Ud", 0.0, 0, 	0, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Carreta", 				   "Ud", 0.0, 2300, 12, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Moto", 				   "Ud", 0.0, 7000, 7, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Balança", 				   "Ud", 0.0, 0, 	0, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Adubadeira Tração Animal","Ud", 0.0, 2500, 5, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Plaina Traseira", 		   "Ud", 0.0, 3000, 10, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Batedor de Cereais", 	   "Ud", 0.0, 3000, 10, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Carroça", 				   "Ud", 2.0, 700, 	8, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Misturador", 			   "Ud", 0.0, 1600, 20, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Veículo", 				   "Ud", 0.0, 0, 	0, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Desintegrador",      	   "Ud", 0.0, 2000, 15, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Arado Tração Animal", 	   "Ud", 0.0, 500, 	15, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Bomba de Água", 		   "Ud", 0.0, 500, 	6, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Eletrificador", 		   "Ud", 0.0, 60, 	5, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Caixa de Água", 		   "Ud", 0.0, 1500, 20, 13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Roçadeira", 			   "Ud", 0.0, 700, 	5, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Computador", 			   "Ud", 0.0, 3500, 5, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Botijão de Sêmen", 	   "Ud", 1.0, 200, 	8, 	13);
INSERT INTO projeto_pesquisa.inventario_maquinas VALUES (0, "Outros", 				   "Ud", 0.0, 2000, 20, 13);

