/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleLogin;
import controle.ControlePerfil;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.dao.PerfilDAO;
import modelo.dao.RotaDAO;
import modelo.dao.UsuarioPerfilDAO;
import modelo.negocio.Perfil;
import modelo.negocio.Usuario;

/**
 *
 * @author Alexandre
 */
public class VisualizarPerfil extends javax.swing.JFrame {
    
    UsuarioPerfilDAO usuarioPerfil;
    PerfilDAO perfilDao;
    ArrayList<Perfil> perfis;
    ArrayList<Integer> idPerfis;
    Usuario usuario;
    
    /**
     * Creates new form VisualizarPerfil
     */
    public VisualizarPerfil() {
        
        initComponents();
        listaPerfis.getSelectionModel().clearSelection();
        setLocationRelativeTo(null);
        this.setResizable(false);
        
        listaPerfis.setShowHorizontalLines(true);
      
        listaPerfis.setColumnSelectionAllowed(false);
        
        usuarioPerfil = new UsuarioPerfilDAO();
        usuario = ControleLogin.getInstance().getUsuario();
        
        idPerfis = new ArrayList<>();
        try {
            perfis = usuarioPerfil.recuperarPerfisPorUsuario(usuario.getId());
        } catch (SQLException ex) {
            System.out.println("Erro em recuperar Perfis Por Usuário - Visualizar Perfil.");
        }
        
        DefaultTableModel model = (DefaultTableModel) listaPerfis.getModel();
        model.setNumRows(0);
                
        for(int i = 0; i < perfis.size(); i++){
            
            idPerfis.add(perfis.get(i).getId());
            
            model.addRow(new Object[]{
                perfis.get(i).getNome(),
                perfis.get(i).getCidade(),
                perfis.get(i).getRota().getRota(),
                perfis.get(i).getTamPropriedade(),
                perfis.get(i).getAreaPecLeite(),
                perfis.get(i).getProdLeiteDiario(),
                perfis.get(i).getEmpPermanentes(),
                perfis.get(i).getNumFamiliares()
            });
            
        }
        
        //Dimension tamanhoTela = Toolkit.getDefaultToolkit().getScreenSize();
        
        //int width = tamanhoTela.width;
        //int height = tamanhoTela.height;
        
        //listaPerfis.setLocation(width / 2, height / 2);
        //listaPerfis.setSize(width / 2, height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnAcessar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPerfis = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Perfis disponíveis");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnAcessar.setText("Acessar");
        btnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessarActionPerformed(evt);
            }
        });

        listaPerfis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Cidade", "Rota", "Tamanho Propriedade", "Área Pecuária Leiteira", "Produção Leite Diária", "Empregados Permanentes", "Número de Familiares"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaPerfis.setColumnSelectionAllowed(true);
        listaPerfis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPerfisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaPerfis);
        listaPerfis.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (listaPerfis.getColumnModel().getColumnCount() > 0) {
            listaPerfis.getColumnModel().getColumn(0).setResizable(false);
            listaPerfis.getColumnModel().getColumn(1).setResizable(false);
            listaPerfis.getColumnModel().getColumn(2).setResizable(false);
            listaPerfis.getColumnModel().getColumn(3).setResizable(false);
            listaPerfis.getColumnModel().getColumn(4).setResizable(false);
            listaPerfis.getColumnModel().getColumn(5).setResizable(false);
            listaPerfis.getColumnModel().getColumn(6).setResizable(false);
            listaPerfis.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(560, 560, 560)
                        .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        // TODO add your handling code here:
        
        if(listaPerfis.getSelectedRow() != -1){
            Perfil atual = new Perfil();
            atual.setId(idPerfis.get(listaPerfis.getSelectedRow()));
            atual.setNome((String) listaPerfis.getModel().getValueAt(listaPerfis.getSelectedRow(), 0));
            atual.setCidade((String) listaPerfis.getModel().getValueAt(listaPerfis.getSelectedRow(), 1));
            try {
                atual.setRota((new RotaDAO()).recuperar((String)listaPerfis.getValueAt(listaPerfis.getSelectedRow(), 2)));
            } catch (SQLException ex) {
                System.out.println("Erro em VisualizarInventario.class - setRota");
            }
            atual.setTamPropriedade((double) listaPerfis.getModel().getValueAt(listaPerfis.getSelectedRow(), 3));
            atual.setAreaPecLeite((double) listaPerfis.getModel().getValueAt(listaPerfis.getSelectedRow(), 4));
            atual.setProdLeiteDiario((double) listaPerfis.getModel().getValueAt(listaPerfis.getSelectedRow(), 5));
            atual.setEmpPermanentes((int) listaPerfis.getModel().getValueAt(listaPerfis.getSelectedRow(), 6));
            atual.setNumFamiliares((int) listaPerfis.getModel().getValueAt(listaPerfis.getSelectedRow(), 7));
        
            ControlePerfil.getInstance().setPerfilSelecionado(atual);

            new MenuPrincipal().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um perfil na tabela!");
        }
        
    }//GEN-LAST:event_btnAcessarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Confirmar logout", JOptionPane.YES_NO_OPTION);
        
        if(escolha == 0){
            ControleLogin.getInstance().fazerLogout();
        
            new Login().setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void listaPerfisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPerfisMouseClicked
        if (evt.getClickCount() == 2) {
            btnAcessarActionPerformed(null);
        }
    }//GEN-LAST:event_listaPerfisMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listaPerfis;
    // End of variables declaration//GEN-END:variables
}
